EShop/Areas/Admin/Controllers/AdminTinDangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EShop.Models;
using PagedList.Core;
using AspNetCoreHero.ToastNotification.Abstractions;
using EShop.Helpper;

namespace EShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminTinDangsController : Controller
    {
        private readonly dbEShopContext _context;

        public INotyfService _notifyService { get; }

        public AdminTinDangsController(dbEShopContext context, INotyfService notyfService)
        {
            _context = context;
            _notifyService = notyfService;
        }

        // GET: Admin/AdminTinDangs
        public IActionResult Index(int? page)
        {
            //Phân trang
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 8;
            var lsTinDangs = _context.TinDangs
                .AsNoTracking()
                .OrderByDescending(x => x.PostId);
            PagedList<TinDang> models = new PagedList<TinDang>(lsTinDangs, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
            //End phân trang
        }

        // GET: Admin/AdminTinDangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tinDang == null)
            {
                return NotFound();
            }

            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminTinDangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] TinDang tinDang, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                //xử lý thumb
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(tinDang.Title) + extension;
                    tinDang.Thumb = await Utilities.UploadFile(fThumb, @"TinDangs", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(tinDang.Thumb)) tinDang.Thumb = "default.jpg";
                //Alias
                tinDang.Alias = Utilities.SEOUrl(tinDang.Title);
                //Ngày tạo
                tinDang.CreatedDate = DateTime.Now;

                _context.Add(tinDang);
                await _context.SaveChangesAsync();

                _notifyService.Success("Success");
                return RedirectToAction(nameof(Index));
            }
            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs.FindAsync(id);
            if (tinDang == null)
            {
                return NotFound();
            }
            return View(tinDang);
        }

        // POST: Admin/AdminTinDangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] TinDang tinDang, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != tinDang.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //xử lý thumb
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string imageName = Utilities.SEOUrl(tinDang.Title) + extension;
                        tinDang.Thumb = await Utilities.UploadFile(fThumb, @"TinDangs", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(tinDang.Thumb)) tinDang.Thumb = "default.jpg";

                    tinDang.Alias = Utilities.SEOUrl(tinDang.Title);
                    tinDang.CreatedDate = DateTime.Now;
                    _context.Update(tinDang);
                    await _context.SaveChangesAsync();
                    _notifyService.Success("Success");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TinDangExists(tinDang.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tinDang == null)
            {
                return NotFound();
            }

            return View(tinDang);
        }

        // POST: Admin/AdminTinDangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tinDang = await _context.TinDangs.FindAsync(id);
            _context.TinDangs.Remove(tinDang);
            await _context.SaveChangesAsync();
            _notifyService.Success("Success");
            return RedirectToAction(nameof(Index));
        }

        private bool TinDangExists(int id)
        {
            return _context.TinDangs.Any(e => e.PostId == id);
        }
    }
}

EShop/Areas/Admin/Views/AdminTinDangs/Create.cshtml
@model EShop.Models.TinDang

@{
    ViewData["Title"] = "Tạo mới tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                <a asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Index" class="breadcrumb-item">Danh sách tin tức</a>

                <span class="breadcrumb-item active">Tạo mới tin</span>
            </nav>
        </div>
    </div>

    <form asp-controller="AdminTinDangs" asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="m-b-15">
                    <button class="btn btn-primary">
                        <i class="anticon anticon-plus-circle"></i>
                        <span>Tạo mới tin tức</span>
                    </button>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN TIN TỨC</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productName">Tiêu đề</label>
                            <input type="text" class="form-control" asp-for="Title">
                        </div>


                        <div class="form-group">
                            <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                            <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                            <span asp-validation-for="Thumb" class="text-danger"></span>
                        </div>
                        <div class="row">
                            <div class="form-group d-flex align-items-center">
                                <div class="checkbox">
                                    <input asp-for="Published" type="checkbox" />
                                    <label for="Published">Public</label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group d-flex align-items-center">
                                <div class="checkbox">
                                    <input asp-for="IsHot" type="checkbox" />
                                    <label for="IsHot">IsHot</label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group d-flex align-items-center">
                                <div class="checkbox">
                                    <input asp-for="IsNewfeed" type="checkbox" />
                                    <label for="IsNewfeed">IsNewfeed</label>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-option">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                            <input type="text" class="form-control" asp-for="MetaDesc">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productFit">MetaKey</label>
                            <input type="text" class="form-control" asp-for="MetaKey">
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-description">
                <div class="card">
                    <div class="card-body">
                        <textarea class="summernote" asp-for="Contents"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </form>

    @section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

EShop/Areas/Admin/Views/AdminTinDangs/Delete.cshtml
@model EShop.Models.TinDang

@{
    ViewData["Title"] = "Xác nhận xóa tin tức: " + Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Index" class="breadcrumb-item">Danh sách tin tức</a>
            <span class="breadcrumb-item active">Xóa tin tức: @Model.Title</span>
        </nav>
    </div>
</div>
<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:100px; width:100px">
                <img src="~/images/TinDangs/@Model.Thumb" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.Title</h4>
                <p class="text-muted m-b-0">ID: #@Model.PostId</p>
            </div>
        </div>
        @* <div class="m-b-15">
        <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Edit" asp-route-id="@Model.PostId">Edit</a>
        </div>*@
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-overview">Chi tiết tin tức</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-images">Ảnh đại diện</a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">XÁC NHẬN XÓA TIN TỨC : @Model.Title.ToUpper()</h4>
                    <form asp-controller="AdminTinDangs" asp-route-id="@Model.PostId" asp-action="Delete">
                        <input type="hidden" asp-for="PostId" />
                        <div class="table-responsive">
                            <table class="product-info-table m-t-20">
                                <tbody>
                                    <tr>
                                        <td>Tiêu đề: </td>
                                        <td class="text-dark font-weight-semibold">@Model.Title</td>
                                    </tr>
                                    <tr>
                                        <td>Tác giả:</td>
                                        <td>@Model.Author</td>
                                    </tr>
                                    <tr>
                                        <td>Ngày tạo:</td>
                                        <td>@Model.CreatedDate</td>
                                    </tr>
                                    <tr>
                                        <td>Alias: </td>
                                        <td>@Model.Alias</td>
                                    </tr>
                                    <tr>
                                        <td>Trạng thái:</td>
                                        <td>
                                            @if (Model.Published)
                                            {
                                                <div class="switch m-r-10">
                                                    <input type="checkbox" id="switch-1" checked="" disabled="">
                                                    <label for="switch-1"></label>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="switch m-r-10">
                                                    <input type="checkbox" id="switch-2" disabled="">
                                                    <label for="switch-2"></label>
                                                </div>
                                            }
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>IsHot:</td>
                                        <td>
                                            @if (Model.IsHot)
                                            {
                                                <div class="switch m-r-10">
                                                    <input type="checkbox" id="switch-1" checked="" disabled="">
                                                    <label for="switch-1"></label>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="switch m-r-10">
                                                    <input type="checkbox" id="switch-2" disabled="">
                                                    <label for="switch-2"></label>
                                                </div>
                                            }

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>IsNewfeed:</td>
                                        <td>
                                            @if (Model.IsNewfeed)
                                            {
                                                <div class="switch m-r-10">
                                                    <input type="checkbox" id="switch-1" checked="" disabled="">
                                                    <label for="switch-1"></label>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="switch m-r-10">
                                                    <input type="checkbox" id="switch-2" disabled="">
                                                    <label for="switch-2"></label>
                                                </div>
                                            }

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Xác nhận xóa: </td>
                                        <td>
                                            <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
            </div>
            @*  <div class="card">
            <div class="card-header">
            <h4 class="card-title">Thông tin mô tả</h4>
            </div>
            <div class="card-body">
            @Html.Raw(Model.Contents)
            </div>
            </div>*@
        </div>
        <div class="tab-pane fade" id="product-images">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <img class="img-fluid" src="~/images/TinDangs/@Model.Thumb" alt="@Model.Title">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EShop/Areas/Admin/Views/AdminTinDangs/Details.cshtml
@model EShop.Models.TinDang

@{
    ViewData["Title"] = "Chi tiết tin tức: " + Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Index" class="breadcrumb-item">Danh sách tin tức</a>
            <span class="breadcrumb-item active">Chi tiết tin tức: @Model.Title</span>
        </nav>
    </div>
</div>
<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:100px; width:100px">
                <img src="~/images/TinDangs/@Model.Thumb" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.Title</h4>
                <p class="text-muted m-b-0">ID: #@Model.PostId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminTinDangs" asp-action="Edit" asp-route-id="@Model.PostId">Edit</a>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-overview">Chi tiết tin tức</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-images">Ảnh đại diện</a>
        </li>
    </ul>
</div>

<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tin tức : @Model.Title</h4>
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td>Tiêu đề: </td>
                                    <td class="text-dark font-weight-semibold">@Model.Title</td>
                                </tr>
                                <tr>
                                    <td>Tác giả:</td>
                                    <td>@Model.Author</td>
                                </tr>
                                <tr>
                                    <td>Ngày tạo:</td>
                                    <td>@Model.CreatedDate</td>
                                </tr>
                                <tr>
                                    <td>Alias: </td>
                                    <td>@Model.Alias</td>
                                </tr>
                                <tr>
                                    <td>Trạng thái:</td>
                                    <td>
                                        @if (Model.Published)
                                        {
                                            <div class="switch m-r-10">
                                                <input type="checkbox" id="switch-1" checked="" disabled="">
                                                <label for="switch-1"></label>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="switch m-r-10">
                                                <input type="checkbox" id="switch-2" disabled="">
                                                <label for="switch-2"></label>
                                            </div>
                                        }
                                    </td>
                                </tr>
                                <tr>
                                    <td>IsHot:</td>
                                    <td>
                                        @if (Model.IsHot)
                                        {
                                            <div class="switch m-r-10">
                                                <input type="checkbox" id="switch-1" checked="" disabled="">
                                                <label for="switch-1"></label>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="switch m-r-10">
                                                <input type="checkbox" id="switch-2" disabled="">
                                                <label for="switch-2"></label>
                                            </div>
                                        }

                                    </td>
                                </tr>
                                <tr>
                                    <td>IsNewfeed:</td>
                                    <td>
                                        @if (Model.IsNewfeed)
                                        {
                                            <div class="switch m-r-10">
                                                <input type="checkbox" id="switch-1" checked="" disabled="">
                                                <label for="switch-1"></label>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="switch m-r-10">
                                                <input type="checkbox" id="switch-2" disabled="">
                                                <label for="switch-2"></label>
                                            </div>
                                        }

                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thông tin mô tả</h4>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Contents)
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-images">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <img class="img-fluid" src="~/images/TinDangs/@Model.Thumb" alt="@Model.Title">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>